### ISSUE TITLE
POST https://sandbox.plaid.com/link/client/get 400 (Bad Request)

### ISSUE THREAD

**Issue by sid3345** [jagodin/personal-finance-app#11]
Getting this errors:
Error: public_key must be a properly formatted, non-empty string.
POST https://sandbox.plaid.com/link/client/get 400 (Bad Request).
POST http://localhost:3000/api/plaid/accounts/transactions

![image](https://user-images.githubusercontent.com/19595612/114269098-7ce6d400-9a22-11eb-88be-2ce3fab44211.png)

Kindly resolve.

**Comment by jagodin** [comment]
Hey Sid, FYI I no longer maintain this project here.

Did you configure the [PlaidLinkButton](https://github.com/jagodin/personal-finance-app/blob/master/client/src/pages/linked-accounts/LinkedAccounts.js#L83-L90)? You'll need to obtain a public key from the Plaid API

**Comment by sid3345** [comment]
Configuring PlaidLinkButton with public key from the Plaid API worked.
